export const SN_UTIL = 'util'
export const UTIL_SHIPMENT_METHODS_UPDATED = SN_UTIL + '/SHIPMENT_METHODS_UPDATED'
export const UTIL_STATUS_UPDATED = SN_UTIL + '/STATUS_UPDATED'
export const UTIL_FACILITIES_LIST_UPDATED = SN_UTIL + '/FACILITIES_LIST_UPDATED'
