export const SN_UTIL = 'util'
export const UTIL_SHIPMENT_METHODS_UPDATED = SN_UTIL + '/SHIPMENT_METHODS_UPDATED'
export const UTIL_FACILITY_LOCATIONS_UPDATED = SN_UTIL + '/FACILITY_LOCATIONS_UPDATED'
export const UTIL_LOCATION_FILTERS_UPDATED = SN_UTIL + '/LOCATION_FILTERS_UPDATED'