export const SN_ORDER = 'order'
export const ORDER_LIST_UPDATED = SN_ORDER + '/LIST_UPDATED'
export const ORDER_FILTERS_UPDATED = SN_ORDER + '/FILTERS_UPDATED'
export const ORDER_CURRENT_UPDATED = SN_ORDER + '/CURRENT_UPDATED'
